### ISSUE TITLE
Fix too many artifacts to upload

### ISSUE THREAD

**Issue by adi-g15** [kaz/arch-repo#5]
As the action uploads the build tree, i saw this warning in my subsequent builds.

**Perhaps the action can just upload the built packages** 🙂 **?**
I did the same, and i don't think there is much slowdown in build part, on the other side the uploading in individual packages and downloading in publish were taking an eternity for me.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/37269665/123702063-4c277580-d880-11eb-84cb-88bd2aa5d51b.png">

**Comment by adi-g15** [comment]
This is the patchfile with my changes, maybe you would like to consider part of it :), didn't open a PR as the changes may not be needed

The changes are in https://github.com/adi-g15/archlinux-repository-boilerplate/tree/patch-2

```patch
--- tasks.sh	2021-06-29 02:26:17.878139613 +0530
+++ Downloads/tasks.sh	2021-06-29 02:29:53.408722671 +0530
@@ -1,11 +1,13 @@
 #!/bin/bash
 
 ARCH=$(uname -m)
+MAKEFLAGS="-j$(nproc)"
 
 : ${BUILD_USER:="builder"}
 
 : ${REPO_DIR:="/tmp/repo"}
 : ${BUILD_DIR:="/tmp/build"}
+: ${PKGS_DIR:="/tmp/_packages_"}
 : ${CCACHE_DIR:="/tmp/ccache"}
 
 : ${GIT_REMOTE:=""}
@@ -49,8 +51,11 @@
 }
 
 package() {
-	sudo -u ${BUILD_USER} mkdir -p "${BUILD_DIR}"
+	sudo -u ${BUILD_USER} mkdir -p "${BUILD_DIR}" "${PKGS_DIR}"
 	sudo -u ${BUILD_USER} yay -Sy --noconfirm --nopgpfetch --mflags "--skippgpcheck" --builddir "${BUILD_DIR}" "$@"
+	# Move package to PKGS_DIR
+	find "${BUILD_DIR}" -name "*.pkg.tar.zst"
+	cp -rv "${BUILD_DIR}/$@/"*.pkg.tar.zst "${PKGS_DIR}/"
 }
 
 repository() {
@@ -61,7 +66,7 @@
 	render_template templates/_config.yml > "${REPO_DIR}/_config.yml"
 
 	cd ${REPO_DIR}/${ARCH}
-	find ${BUILD_DIR} -name *.pkg.tar.zst -exec cp -f {} . \;
+	find ${PKGS_DIR} -name *.pkg.tar.zst -exec cp -f {} . \;
 	repo-add "${GITHUB_REPO_OWNER}.db.tar.gz" *.pkg.tar.zst
 }
 
```

**Comment by kaz** [comment]
Thank you for your feedback :)

> Perhaps the action can just upload the built packages 🙂 ?

You're right, uploading whole build-tree was not needed.
I'd be glad if you could open a PR fixing this issue!

**Comment by adi-g15** [comment]
I have created the PR.

Thanks @kaz though, your project made it easier for me to update packages 😄:+1:

**Comment by adi-g15** [comment]
> I have created the PR.
> 
> Thanks @kaz though, your project made it easier for me to update packages smile+1
